<a href="https://colab.research.google.com/github/StudentCoder2409/bank-marketing-churn-analysis/blob/main/churn_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import os
os.listdir()

['.config', 'bank-additional-full.csv', 'sample_data']

In [ ]:
df = pd.read_csv("bank-additional-full.csv", sep=';', engine='python', on_bad_lines='skip')
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df.info()
df.columns
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df['y'].value_counts(normalize=True)

y
no     0.887346
yes    0.112654
Name: proportion, dtype: float64

In [ ]:
df['churn'] = df['y'].apply(lambda x: 1 if x == 'no' else 0)

In [ ]:
df.groupby('contact')['churn'].mean()

contact
cellular     0.852624
telephone    0.947687
Name: churn, dtype: float64

In [ ]:
df.groupby('month')['churn'].mean().sort_values()

month
mar    0.494505
dec    0.510989
sep    0.550877
oct    0.561281
apr    0.795213
aug    0.893979
jun    0.894885
nov    0.898561
jul    0.909534
may    0.935653
Name: churn, dtype: float64

In [ ]:
df.groupby('housing')['churn'].mean()

housing
no         0.891204
unknown    0.891919
yes        0.883806
Name: churn, dtype: float64

In [ ]:
df.groupby('loan')['churn'].mean()

loan
no         0.886598
unknown    0.891919
yes        0.890685
Name: churn, dtype: float64

In [ ]:
df.groupby('job')['churn'].mean().sort_values(ascending=False)

job
blue-collar      0.931057
services         0.918619
entrepreneur     0.914835
housemaid        0.900000
self-employed    0.895144
technician       0.891740
unknown          0.887879
management       0.887825
admin.           0.870274
unemployed       0.857988
retired          0.747674
student          0.685714
Name: churn, dtype: float64

In [ ]:
total_customers = len(df)
conversions = (df['y'] == 'yes').sum()
non_conversions = (df['y'] == 'no').sum()

total_customers, conversions, non_conversions

(41188, np.int64(4640), np.int64(36548))

In [ ]:
total_customers = len(df)
conversions = (df['y'] == 'yes').sum()
non_conversions = (df['y'] == 'no').sum()

value_per_customer = 1000

revenue_generated = conversions * value_per_customer
revenue_lost = non_conversions * value_per_customer

revenue_generated, revenue_lost

(np.int64(4640000), np.int64(36548000))

In [ ]:
print(f"Revenue Generated: ${revenue_generated:,.0f}")
print(f"Revenue Lost: ${revenue_lost:,.0f}")

Revenue Generated: $4,640,000
Revenue Lost: $36,548,000

In [ ]:
df.groupby('marital')['churn'].mean().sort_values(ascending=False)

marital
married     0.898427
divorced    0.896791
single      0.859959
unknown     0.850000
Name: churn, dtype: float64

In [ ]:
df.to_csv("Cleaned_churn_data.csv", index=False)